name: caglan
max_trials: 5
epochs: 1
buffer_size: 35000
batch_size: 256
image_size: !!python/tuple [64, 64, 3]
unit: 64
generator_layer_iterator:
  - 3
discriminator_layer_iterator:
  - 3
  - 4
kernel:
  - 3
  - 5
  - 8
dropout_ratio:
  - 0.3
  - 0.5
lr_generator:
  - !!float 1e-4
  - 0.01
  - 0.001
lr_discriminator:
  - !!float  1e-4
  - 0.01
  - 0.001
noise_dimension:
  - 50
  - 100
  - 500
